version: '2'
services:

  web:
    image: "bsimpson53/nxfc_web:latest"
    ports:
      - "3000:3000"
      - "35729:35729"
      - "5858:5858"
      - "2368:2368"
    volumes:
      - "../modules:/home/app/modules" 
      - "../uploads:/home/app/uploads"
    depends_on:
      - nxfc_mongo
    environment:
      - NODE_ENV="development"
      - OWNER="admin"
      - MONGO_ADDR_VAR=MONGO
      - MONGO=nxfc_mongo

  worker:
    build:
      context: ..
      dockerfile: worker/Dockerfile
    ports: 
      - 4000:4000
    depends_on:
      - nxfc_mongo
    environment:
      - NODE_ENV="development"
      - MONGO_ADDR_VAR=MONGO
      - MONGO=nxfc_mongo
    
  nxfc_mongo:
    image: "newcrossfoodcoop/nxfc-mongo"
    ports:
      - "27017:27017"
